package com.italia.enm;

/**
 * 
 * @author Mark Italia
 * @version 1.0
 * @since 11/14/2020
 *
 */
public enum CashType {
	//when adding update CashProcess.class method supplyAddDtls and amountCharge
	ACCOMMODATION_PAID(12, "ACCOMMODATION PAID"),
	ALL_EXPENSE(35,"ALL EXPENSE"),
	ALL_INCOME(34,"ALL INCOME"),
	AMOUNT_PAID_SUPPLIER(16, "AMOUNT PAID TO SUPPLIER"),
	CASH_GROCERRY_EXPENSE(19, "CASH GROCERRY EXPENSE"),
	CASH_IN_TODAY(1, "CASH IN FOR TODAY"),
	CASH_ADVANCE_EMPLOYEE(5, "CASH ADVANCE EMPLOYEE"),
	CASH_EXPENSES(2, "CASH EXPENSES"),
	CASH_OTHER_INCOME(4, "CASH FROM OTHER INCOME"),
	CASH_OUT(36, "CASH OUT"),
	COMPANY_EXPENSE_ACTIVITY(25, "COMPANY EXPENSE ACTIVITIES"),
	EMPLOYEE_SALARY(6, "EMPLOYEE SALARY"),
	ENTRANCE_TICKET(10, "ENTRANCE TICKET"),
	EVENT_RESERVATION(7, "EVENT RESERVATION DOWNPAYMENT"),
	FARE(17,"FARE"),
	GASOLINE(20, "GASOLINE"),
	MATERIAL_EXPENSE(22, "MATERIAL EXPENSE"),
	MERRIENDA(18, "MERRIENDA"),
	MINERAL_WATER_GALLON_ORDER(31, "MINERAL WATER GALLON ORDER"),
	NATIVE_CHICKEN_EXPENSES(26, "NATIVE CHICKEN EXPENSES"),
	ORDER_CREDIT(43, "ORDER CREDIT"),
	PAID_BAR_ORDER(30, "PAID BAR ORDER"),
	PAID_CREDIT(44, "PAID CREDIT"),
	PAYMENT_TO_BUYNSELL(28, "PAYMENT TO MATT BUY AND SELL"),
	PAYMENT_TO_TALENT(24, "PAYMENT TO TALENT"),
	GCASH(37,"RECEIVED PAYMENT FROM GLOBE GCASH"),
	BDO(38, "RECEIVED PAYMENT FROM BDO BANK"),
	RCBC(39, "RECEIVED PAYMENT FROM RCBC BANK"),
	BPI(40, "RECEIVED PAYMENT FROM BPI BANK"),
	LANDBANK(41, "RECEIVED PAYMENT FROM LANDBANK"),
	DBP(42, "RECEIVED PAYMENT FROM DBP BANK"),
	RENOVATION_EXPENSE(23, "RENOVATION EXPENSE"),
	RESTO_ORDER(3, "RESTAURANT ORDER PAID"),
	ROOM_RESERVATION(8, "ROOM RESERVATION DOWNPAYMENT"),
	SACK_RICE_EXPENSE(32, "SACK RICE EXPENSE"),
	SOLANE(21, "SOLINE"),
	SOUVENIR_CAPITAL(45, "SOUVENIR CAPITAL"),
	SOUVENIR_EXPENSE(46, "SOUVENIR EXPENSES"),
	SOUVENIR_INCOME(47, "SOUVENIR INCOME"),
	SOUVENIR_ADD_CAPITAL(48, "SOUVENIR ADDITIONAL CAPITAL"),
	SOUVENIR_MINUS_CAPITAL(49, "SOUVENIR MINUS CAPITAL"),
	TILAPIA_EXPENSES(27, "TILAPIA EXPENSES"),
	UNPAID_ACCOMMODATION(11, "UNPAID ACCOMMODATION"),
	UNPAID_BAR_ORDER(29, "UNPAID BAR ORDER"),
	UNPAID_BOOKING_SEMINAR(14, "UNPAID BOOKING SEMINAR"),
	UNPAID_ORDER(9, "UNPAID ORDER"),
	UNPAID_ENTRANCE(13, "UNPAID ENTRANCE"),
	UNPAID_PAYMENT_SUPPLIER(15, "UNPAID PAYMENT TO SUPPLIER"),
	VILLA_SHARE_INCOME(33,"VILLA SHARE INCOME");
	
	private int id;
	private String name;
	
	public int getId() {
		return id;
	}
	
	public String getName() {
		return name;
	}
	
	private CashType(int id, String name) {
		this.id = id;
		this.name = name;
	}
	
	public static CashType containId(int id) {
		for(CashType t : CashType.values()) {
			if(t.getId()==id) {
				return t;
			}
		}
		return RESTO_ORDER;
	}
	
	public static CashType containName(String name) {
		for(CashType t : CashType.values()) {
			if(t.getName().equalsIgnoreCase(name)) {
				return t;
			}
		}
		return RESTO_ORDER;
	}
	
	
}
